In [1]:
# install python - numpy

In [2]:
#install python package
#pip install numpy

In [3]:
#calling numpy and make numpy change name to np
import numpy as np

In [4]:
print('hi')

hi


In [5]:
list=[1,2,3,4]

In [6]:
print(list)

[1, 2, 3, 4]


In [7]:
type(list)

list

In [8]:
#to show hoy much function in numpy
#dir(np)

In [9]:
#to find the help from numpy 
#help(np)

In [10]:
arr=np.array(list)

In [11]:
print(arr)
print(type(arr))

[1 2 3 4]
<class 'numpy.ndarray'>


In [12]:
arr.shape

(4,)

In [13]:
my_lst1=[1,2,3,4,5]
my_lst2=[2,3,4,5,6]
my_lst3=[9,7,6,8,9]

arr = np.array([my_lst1,my_lst2,my_lst3])



In [14]:
arr


array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [15]:
print(type(arr))

<class 'numpy.ndarray'>


In [16]:
arr.shape

(3, 5)

In [17]:
arr.size

15

In [18]:
list=[1,2,3,4,5]
arr=np.array(list)

In [19]:
print(arr[3])

4


In [20]:
print(arr[1])

2


In [21]:
print("third element is ",arr[3])

third element is  4


In [22]:
#access of 2d array
my_lst1=[1,2,3,4,5]
my_lst2=[2,3,4,5,6]
my_lst3=[9,7,6,8,9]

arr = np.array([my_lst1,my_lst2,my_lst3])



In [23]:
arr


array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [24]:
arr[0,2]


3

In [25]:
arr[2,4]


9

In [26]:
arr[1,4]

6

In [27]:
arr = np.array([[1,2,3],[4,5,6]])
#print array
print(arr)
#print size
print(arr.size)
#print shape
print(arr.shape)
#first row first elemnt
print(arr[0,0])
#scnd row third elemnt
print(arr[1,2])




[[1 2 3]
 [4 5 6]]
6
(2, 3)
1
6


In [28]:
#acces 5d array
list1= [1,2,3,4,5]
list2= [2,3,4,5,6]
list3= [9,7,6,8,9]
list4=[2,4,6,8,0]
list5=[1,3,5,7,9]
arr= np.array([list1,list2,list3,list4,list5])

In [29]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9],
       [2, 4, 6, 8, 0],
       [1, 3, 5, 7, 9]])

In [30]:
arr.shape

(5, 5)

In [31]:
arr.size

25

In [32]:
arr[2,4]


9

In [33]:
arr[1,4]

6

In [34]:
valArr = np.array([[1,2,3],[4,5,6]])
print(valArr)
valArr[1,-2]


[[1 2 3]
 [4 5 6]]


5

In [35]:
#numpy slicing
list=[1,2,3,4,5,6]


In [36]:
arr=np.array(list)

In [37]:
arr

array([1, 2, 3, 4, 5, 6])

In [38]:
arr[0:3]


array([1, 2, 3])

In [39]:
arr[:3]

array([1, 2, 3])

In [40]:
arr[:-1]

array([1, 2, 3, 4, 5])

In [41]:
arr[::-1]

array([6, 5, 4, 3, 2, 1])

In [42]:
arr[-3:-1]

array([4, 5])

In [43]:
list=[1,2,3,4,5,6]
arr=np.array(list)

In [44]:
arr[::2]

array([1, 3, 5])

In [45]:
arr[1::2]

array([2, 4, 6])

In [46]:
list1=[1,2,3,4,5]
list2=[6,7,8,9,0]
arr=np.array([list1,list2])


In [47]:
arr

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0]])

In [48]:
arr[1:,1:4]

array([[7, 8, 9]])

In [49]:
#arranging array
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
np.arange(11,20)

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [51]:
#skip the 2 step with arranging
np.arange(11,20,2)

array([11, 13, 15, 17, 19])

In [52]:
#convert int array type to string
arr=np.array([1,2,3,4],dtype= 'S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [53]:
x=np.array([[1,2],[3,4]])
y=np.array([[5,6],[7,8]])
print(x)
print(" ")
print(y)

[[1 2]
 [3 4]]
 
[[5 6]
 [7 8]]


In [54]:
x+y

array([[ 6,  8],
       [10, 12]])

In [55]:
x-y

array([[-4, -4],
       [-4, -4]])

In [56]:
np.add(x,y)

array([[ 6,  8],
       [10, 12]])

In [57]:
np.multiply(x,y)



array([[ 5, 12],
       [21, 32]])

In [58]:
np.divide(x,y)


array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [59]:
np.divmod(x,y)

(array([[0, 0],
        [0, 0]], dtype=int32),
 array([[1, 2],
        [3, 4]], dtype=int32))

In [60]:
np.square(x,y)

array([[ 1,  4],
       [ 9, 16]])

In [61]:
 np.log(x)

array([[0.        , 0.69314718],
       [1.09861229, 1.38629436]])

In [62]:
x

array([[1, 2],
       [3, 4]])

In [63]:
np.floor(x)


array([[1., 2.],
       [3., 4.]])

In [64]:
np.round(x)

array([[1, 2],
       [3, 4]])

In [65]:
k=np.array([[1.5,2.2,3.4,5.8]])

In [66]:
k

array([[1.5, 2.2, 3.4, 5.8]])

In [67]:
np.round(k)

array([[2., 2., 3., 6.]])

In [68]:
#dotproduct of array
x=np.array([1,2])
y=np.array([3,4])

np.dot(x,y)


11

In [69]:
x=np.array([[1,2],[3,4]])
y=np.array([[5,6],[7,8]])
np.dot(x,y)

array([[19, 22],
       [43, 50]])

In [70]:
#finding sum of rowise
x=np.array([[1,2,3],[4,5,6],[7,8,9]])
np.sum(x,axis=0)

array([12, 15, 18])

In [71]:
#finding sum of column wise
print(x)
np.sum(x,axis=1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([ 6, 15, 24])

In [72]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [73]:
x.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [74]:
#concaneating two array
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
np.concatenate((arr1,arr2))

array([1, 2, 3, 4, 5, 6])